CREATE TABLE category
(
  Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE subcategory
(
  Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL
);


CREATE TABLE items
(
 Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  Name VARCHAR(255) NOT NULL
);